Document: vaporos-flatpak-manager
Title: Debian vaporos-flatpak-manager Manual
Author: <insert document author here>
Abstract: This manual describes what vaporos-flatpak-manager is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/vaporos-flatpak-manager/vaporos-flatpak-manager.sgml.gz

Format: postscript
Files: /usr/share/doc/vaporos-flatpak-manager/vaporos-flatpak-manager.ps.gz

Format: text
Files: /usr/share/doc/vaporos-flatpak-manager/vaporos-flatpak-manager.text.gz

Format: HTML
Index: /usr/share/doc/vaporos-flatpak-manager/html/index.html
Files: /usr/share/doc/vaporos-flatpak-manager/html/*.html
